server:
  port: 7800
spring:
  datasource:
    url: jdbc:mysql://192.168.1.3:3306/blog
    username: mehdi
    password: Mehdi1999@
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

jwt:
  secret: '=rN2nVkRG{<@PN=RcgFJrK?$'