server:
  port: 8036
spring:
  datasource:
    url: jdbc:mysql://localhost/security?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: "root"
    password: ""
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      validation-query: SELECT 1
      test-while-idle: true
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy